name: build-preview
run-name: build pull request preview

on:
  # run when called from another workflow
  workflow_call:

  # run if user manually requests it
  workflow_dispatch:

# variables
env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write
  pull-requests: write

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure Docker daemon.json exists
        run: |
          sudo mkdir -p /etc/docker
          if [ ! -f /etc/docker/daemon.json ]; then
            echo '{}' | sudo tee /etc/docker/daemon.json > /dev/null
          fi
      
      - name: Debug dump
        if: runner.debug == '1'
        uses: crazy-max/ghaction-dump-context@158bbf4d6158a44a7e13f76295dc55a69e481a6e #v2
        continue-on-error: true

      - name: Checkout branch contents
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.01
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Install Ruby packages
        if: github.event.action != 'closed'
        uses: ruby/setup-ruby@ae195bbe749a7cef685ac729197124a48305c1cb #v1.276.0
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Get Pages url
        if: github.event.action != 'closed'
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b #v5

      - uses: jwalton/gh-find-current-pr@89ee5799558265a1e0e31fab792ebb4ee91c016b #v1.3.3
        if: github.event.action != 'closed'
        id: pr
        with:
          state: all

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 #v3.23

      - name: Build preview version of site
        if: github.event.action != 'closed'
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}/${{ env.PREVIEWS_FOLDER }}/pr-${{ env.pr }}"
        env:
          pr: ${{ steps.pr.outputs.pr }}

      - name: Commit preview to Pages branch
        uses: rossjrw/pr-preview-action@3e4ed158ecbf7f58513abc0dc15a4ad3b0e18ee5 #v1.72
        with:
          source-dir: _site
          umbrella-dir: ${{ env.PREVIEWS_FOLDER }}
