name: update-url
run-name: update site after url change

on:
  # run when called from another workflow
  workflow_call:
    outputs:
      changed:
        value: ${{ jobs.update-url.outputs.changed }}

  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-url:
    runs-on: ubuntu-latest

    steps:
      - name: Debug dump
        uses: crazy-max/ghaction-dump-context@158bbf4d6158a44a7e13f76295dc55a69e481a6e #v2

      - name: Get Pages url
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b #v5

      - name: Checkout branch contents
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.01

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 #v3.23

      # update link to site in readme
      - name: Update readme
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd #v8.0.0
        with:
          script: |
            const { readFileSync, writeFileSync } = require("fs");
            const file = "README.md";
            let contents = readFileSync(file).toString();
            const find = /\*\*\[.*\]\(.*\)\*\*/;
            const host = "${{ steps.pages.outputs.host }}";
            const path = "${{ steps.pages.outputs.base_path }}";
            const url = "${{ steps.pages.outputs.base_url }}";
            const replace = `**[${host}${path}](${url})**`;
            if (contents.match(find))
              contents = contents.replace(find, replace);
            else
              contents = `Visit ${replace} ðŸš€\n\n` + contents;
            writeFileSync(file, contents);

      - name: Check if readme changed
        id: changed
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf #v20.04
        with:
          files: |
            README.md

      - name: Commit changed files
        if: steps.changed.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 #v7.1
        with:
          commit_message: "Update url"

    outputs:
      changed: ${{ steps.changed.outputs.files_changed }}
