name: update-citations
run-name: update citations

on:
  # run when called from another workflow
  workflow_call:
    inputs:
      open-pr:
        type: boolean
    outputs:
      changed:
        value: ${{ jobs.update-citations.outputs.changed }}

  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  FORCE_COLOR: true
  GOOGLE_SCHOLAR_API_KEY: ${{ secrets.GOOGLE_SCHOLAR_API_KEY }}

jobs:
  update-citations:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Ensure Docker daemon.json exists
        run: |
          sudo mkdir -p /etc/docker
          if [ ! -f /etc/docker/daemon.json ]; then
            echo '{}' | sudo tee /etc/docker/daemon.json > /dev/null
          fi
      
      - name: Debug dump
        if: runner.debug == '1'
        uses: crazy-max/ghaction-dump-context@158bbf4d6158a44a7e13f76295dc55a69e481a6e #v2
        continue-on-error: true

      - name: Checkout branch contents
        if: github.event.action != 'closed'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.01
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Setup Python
        if: github.event.action != 'closed'
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 #v6.1.0
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Install Python packages
        if: github.event.action != 'closed'
        run: |
          python -m pip install --upgrade --requirement ./_cite/requirements.txt

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 #v3.23

      - name: Build updated citations
        if: github.event.action != 'closed'
        run: python _cite/cite.py
        timeout-minutes: 15

      - name: Commit cache
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 #v7.1
        with:
          file_pattern: "**/.cache/**"
          commit_message: "Commit cache"

      - name: Check if citations changed
        if: github.event.action != 'closed'
        id: changed
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf #v20.04
        with:
          files: |
            _data/citations.yaml

      - name: Commit updated citations to branch
        if: |
          github.event.action != 'closed' &&
          steps.changed.outputs.files_changed == 'true' &&
          inputs.open-pr != true
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 #v7.1
        with:
          commit_message: "Update citations"

      - name: Open pull request with updated citations
        if: |
          github.event.action != 'closed' &&
          steps.changed.outputs.files_changed == 'true' &&
          inputs.open-pr == true
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 #v8.0.0
        with:
          branch: citation-update
          title: Periodic citation update
          body: |
            To see a live preview of this PR, close (don't merge) and reopen it.

    outputs:
      changed: ${{ steps.changed.outputs.files_changed || false }}
